-- Gen251 -- every one of the 251 obtainable renewably, in one save, on one
-- cartridge, without trading, while every vanilla encounter keeps its exact
-- vanilla behaviour.
--
-- The wiring lives here; the deciding lives elsewhere:
--
--   placements.lua  the single source of truth: species -> map, method,
--                   tier, band, gate, justification.  SET B is generated by
--                   tools/build_placements2.py from both pret trees.
--   build.lua       placements + the live tables -> substitution rows, and
--                   the "is this species already renewable here?" question
--                   that makes version detection unnecessary
--   roll.lua        the substitution itself, and the promise that a map with
--                   nothing to substitute costs zero draws
--
-- Gen 2 only.  Its Gen 1 counterpart is ALL 151, which is a different table
-- against different gaps, and the two never install together.

local mod = ...

local Gen251 = {}

local MOD_ID = "gen251"

-- Rarity weights, parts per Roll.RARITY_SCALE.  The same three tiers Gen151
-- uses and for the same reasons: the ninth vanilla slot for a species that
-- should read as a resident of the route, the tenth for one the cartridge
-- treated as unique, and a step between them for the gift mons.
local TIERS = { UNCOMMON = 430, RARE = 250, VERY_RARE = 117 }

-- A file this module ships, compiled in this mod's own sandbox.  A mod's
-- directory is not on package.path, so mod:read plus load is the documented
-- way to reach one.
--
-- Every name here is written out in full, `gen2/` and all, rather than
-- assembled from a prefix.  ALL 251 lives inside the Gen151 repository beside
-- ALL 151, and the two ship files of the same NAME with different contents --
-- build.lua, placements.lua and roll.lua are each a different table for a
-- different cartridge.  `mod:read` is rooted at the mod's own folder (the
-- bundle's facade does the same at runtime/facade.lua:77), so a bare
-- "build.lua" here would quietly load Kanto's: it compiles, and it is wrong in
-- a way nothing would report.
--
-- Spelled out rather than prefixed because the bundle's tools/check.py reads
-- these names STATICALLY to prove every file a feature loads is actually
-- shipped.  A runtime prefix is invisible to it, and it duly resolved three of
-- these five against Kanto's copies and called the other two missing.  A
-- literal path is honest to the reader and to the checker at once.
local function submodule(name)
  local source = mod and mod:read(name)
  if not source then
    if mod then
      mod.log:error("%s is missing -- the whole spawn layer is skipped", name)
    end
    return nil
  end
  local chunk, err = load(source, "@" .. name)
  if not chunk then
    mod.log:error("%s did not compile: %s", name, tostring(err))
    return nil
  end
  local okCall, value = pcall(chunk)
  if not okCall then
    mod.log:error("%s failed to load: %s", name, tostring(value))
    return nil
  end
  return value
end

-- "gen1" | "gs" | "crystal".  Asked rather than tested for, so a cartridge
-- nobody has thought of yet still gets a right answer.
local function lineage()
  local okReq, GameVersion = pcall(require, "src.core.GameVersion")
  if not okReq or type(GameVersion) ~= "table" then return nil end
  if type(GameVersion.engine) ~= "function" then return nil end
  local okCall, value = pcall(GameVersion.engine)
  return okCall and value or nil
end

-- Gold keys wild encounters by KIND first and by map second, so the registry
-- enumerates kinds -- `grass`, `water`, `fishGroups`, `trees`, `treeSets`,
-- `bugContest` and the swarm shadows -- rather than maps.  Reassembled here
-- into the one table build.lua reads, which is also the shape ctx.tables has.
local function liveTables()
  local out = {}
  for kind, value in mod.content.encounters:each() do
    out[kind] = value
  end
  return out
end

local function livePokemon()
  local out = {}
  for id, def in mod.content.pokemon:each() do
    out[id] = def
  end
  return out
end

function Gen251.install()
  if lineage() == "gen1" then return end

  local Placements = submodule("gen2/placements.lua")
  local Build = submodule("gen2/build.lua")
  local Roll = submodule("gen2/roll.lua")
  local Trade = submodule("gen2/trade.lua")
  local Statics = submodule("gen2/statics.lua")
  if not (Placements and Build and Roll and Trade and Statics) then return end

  -- The ten trade evolutions, which are a missing cable rather than a missing
  -- habitat and so are answered here rather than in the placement table.
  Trade.install(mod)

  -- LUGIA, HO-OH and SNORLAX stay until they are caught, and RAIKOU and ENTEI
  -- go back to roaming.  Nothing here writes an event flag: Gen 2's
  -- EVENT_FOUGHT_* are load-bearing for progression a player would not
  -- expect to lose.
  Statics.install(mod)

  local roll = Roll.new()
  local installed = false

  -- Built once the data is merged rather than at install time: a mod loaded
  -- before another one's encounter patch would otherwise decide renewability
  -- against half a table and place a species the other mod was about to
  -- provide.  game.ready is after every merge.
  local function build()
    if installed then return end
    installed = true

    local okBuild, out = pcall(Build.rows, Placements, liveTables(),
                               livePokemon(),
                               { tiers = TIERS, lineage = lineage() })
    if not okBuild then
      mod.log:error("the placement table did not build: %s -- no spawns are "
        .. "added and vanilla encounters are untouched", tostring(out))
      return
    end

    for _, row in ipairs(out.rows) do
      roll:add(row.map, row.terrain, {
        species = row.species, levels = row.levels, weight = row.weight,
      })
    end

    -- A row whose map has no table on this cartridge is a bug in the table,
    -- not a fact about the save, so it is said out loud.  A row skipped
    -- because its species is already renewable is the opposite -- that is the
    -- design working -- so it is only counted.
    for _, row in ipairs(out.unplaced) do
      mod.log:warn("%s has nowhere to go on this cartridge: %s has %s",
        row.species, row.map, row.why)
    end
    mod.log:info("%d placement(s) applied, %d already renewable here",
      #out.rows, #out.skipped)

    mod.exports.rows = out.rows
    mod.exports.skipped = out.skipped
    mod.exports.enabled = true
    mod.exports.id = MOD_ID
  end

  mod.events:on("game.ready", build)
  mod.events:on("save.loaded", build)

  -- The stream, guarded the way the roll layer promises: `rng` is only ever
  -- reached when a map has an active row, so a cartridge with nothing placed
  -- on it draws exactly what a clean install draws.
  local function rng(low, high)
    if love and love.math and love.math.random then
      return love.math.random(low, high)
    end
    return math.random(low, high)
  end

  mod.hooks:wrap("encounter.roll", function(vanilla, tables, ctx)
    if not installed then return vanilla(tables, ctx) end
    return roll:roll(vanilla, tables, ctx, rng)
  end)
end

if mod then Gen251.install() end

return Gen251
