-- GENERATED by tools/build_hints.py from placements.lua.  Do not hand-edit:
-- a hint that disagrees with the spawn it describes is worse than no hint,
-- and the only way to guarantee they agree is to derive one from the other
-- (SPEC 6b).
--
-- The vocabulary is generated; the sentences are assembled at runtime from
-- the RESOLVED rows, because the levels a row lands on depend on which
-- cartridge is running.  A hint that named a band would be right on Red and
-- wrong on Yellow.

local H = {}

-- Names that fit the 18-column text box, using Kanto's own abbreviations
-- where the town map already has one.
H.MAPS = {
  CERULEAN_CAVE_1F = "CERULEAN CAVE 1F",
  CERULEAN_CAVE_B1F = "CERULEAN CAVE B1F",
  POKEMON_MANSION_1F = "MANSION 1F",
  POKEMON_MANSION_2F = "MANSION 2F",
  POKEMON_MANSION_3F = "MANSION 3F",
  POKEMON_MANSION_B1F = "MANSION B1F",
  POWER_PLANT = "POWER PLANT",
  ROCK_TUNNEL_1F = "ROCK TUNNEL 1F",
  ROUTE_10 = "ROUTE 10",
  ROUTE_11 = "ROUTE 11",
  ROUTE_12 = "ROUTE 12",
  ROUTE_13 = "ROUTE 13",
  ROUTE_14 = "ROUTE 14",
  ROUTE_15 = "ROUTE 15",
  ROUTE_17 = "ROUTE 17",
  ROUTE_2 = "ROUTE 2",
  ROUTE_20 = "ROUTE 20",
  ROUTE_23 = "ROUTE 23",
  ROUTE_24 = "ROUTE 24",
  ROUTE_25 = "ROUTE 25",
  ROUTE_3 = "ROUTE 3",
  ROUTE_4 = "ROUTE 4",
  ROUTE_5 = "ROUTE 5",
  ROUTE_6 = "ROUTE 6",
  ROUTE_7 = "ROUTE 7",
  ROUTE_8 = "ROUTE 8",
  ROUTE_9 = "ROUTE 9",
  SAFARI_ZONE_CENTER = "SAFARI CENTER",
  SAFARI_ZONE_EAST = "SAFARI EAST",
  SEAFOAM_ISLANDS_1F = "SEAFOAM IS. 1F",
  SEAFOAM_ISLANDS_B2F = "SEAFOAM IS. B2F",
  SEAFOAM_ISLANDS_B3F = "SEAFOAM IS. B3F",
  SEAFOAM_ISLANDS_B4F = "SEAFOAM IS. B4F",
  VICTORY_ROAD_1F = "VICTORY ROAD 1F",
  VICTORY_ROAD_2F = "VICTORY ROAD 2F",
  VICTORY_ROAD_3F = "VICTORY ROAD 3F",
  VIRIDIAN_FOREST = "VIRIDIAN FOREST",
}

H.METHODS = {
  grass = "in the grass",
  water = "out on the water",
  super_rod = "with a SUPER ROD",
}

H.TIERS = {
  UNCOMMON = "uncommon",
  RARE = "rare",
  VERY_RARE = "very rare",
}

function H.mapName(mapId)
  return H.MAPS[mapId] or (mapId:gsub("_", " "))
end

local function levelRange(levels)
  if not levels or #levels == 0 then return nil end
  local lo, hi = levels[1], levels[1]
  for _, level in ipairs(levels) do
    if level < lo then lo = level end
    if level > hi then hi = level end
  end
  if lo == hi then return ("Lv%d"):format(lo) end
  return ("Lv%d-%d"):format(lo, hi)
end

H.levelRange = levelRange

-- One row -> the pages of a text box.  \n breaks a line, \f breaks a page,
-- which is the engine's own idiom (src/render/TextBox.lua).
function H.describe(row)
  local where = H.mapName(row.map)
  local how = H.METHODS[row.method or (row.rod and "super_rod")] or ""
  local band = levelRange(row.levels)
  local first = where
  if band then first = first .. ", " .. band end
  local text = first .. "\n" .. how

  local tier = H.TIERS[row.tier]
  local second = ""
  if tier then
    second = tier:sub(1, 1):upper() .. tier:sub(2) .. " there."
  end
  if row.gate then
    second = (second ~= "" and (second .. "\n") or "") .. "Needs " .. row.gate
  end
  if second ~= "" then text = text .. "\f" .. second end
  return text
end

-- Every place one species turns up, as one box.
function H.forSpecies(rows, speciesName)
  if #rows == 0 then
    return speciesName .. " has no\nGEN151 spawn."
  end
  local parts = {}
  for _, row in ipairs(rows) do parts[#parts + 1] = H.describe(row) end
  return table.concat(parts, "\f")
end

-- The strip under the AREA map.  Not a sentence: the blinking nests have
-- already said WHERE, so this is the rest of the answer in as few glyphs as
-- will carry it -- how you fish it out, roughly what level, how often, and
-- what you need to be carrying to get there at all.
H.SHORT_METHODS = {
  grass = "GRASS",
  water = "SURF",
  super_rod = "SUPER ROD",
}

H.SHORT_TIERS = {
  UNCOMMON = "UNCOMMON",
  RARE = "RARE",
  VERY_RARE = "VERY RARE",
}

-- rows for ONE species -> up to two lines.  nil when there is nothing to say,
-- which is how a species this mod never placed keeps the vanilla AREA screen
-- exactly as it was.
--
-- `cols` is the budget for the SECOND line, which is the tight one: the box
-- puts its blinking prompt in that line's last column.  Nothing is truncated
-- here -- the caller clamps, in the pixels the glyphs actually draw, because
-- a variable-advance font makes "columns" and "bytes" different numbers.
function H.caption(rows, cols)
  if not rows or #rows == 0 then return nil end
  cols = cols or 19

  -- Every row for a species shares a method far more often than not; when
  -- they do not, the first one is the one the level band belongs to, so
  -- naming a second method here would attach it to the wrong numbers.
  local row = rows[1]
  local how = H.SHORT_METHODS[row.method or (row.rod and "super_rod")] or ""
  local band = levelRange(row.levels)
  local first = band and (how .. "  " .. band) or how

  -- The gate outranks the rarity: "RARE" is a hunt, but "you cannot be here
  -- without SURF" is the difference between a hunt and a wasted afternoon.
  local second
  if row.gate then
    second = "NEEDS " .. tostring(row.gate):upper()
  else
    second = H.SHORT_TIERS[row.tier]
    if second and #rows > 1 then
      -- one space, not two: the second line has one column less than the
      -- first to spend, and "VERY RARE  2 SPOTS" is exactly one over
      local more = (" %d SPOTS"):format(#rows)
      if #second + #more <= cols then second = second .. more end
    end
  end

  local out = { first }
  if second and second ~= "" then out[2] = second end
  return out
end

return H
