#!/usr/bin/env python3
"""Derive SET B -- the version exclusives -- and splice it into placements.lua.

    python3 tools/build_placements2.py --pokegold <dir> --pokecrystal <dir>
                                       [--check]

SET B needs no taste, which is the whole reason it is generated.  A version
exclusive is missing on one cartridge and present on another, so its placement
is simply the map the OTHER cartridge puts it on -- the same game, the same
species, the same map -- and there is nothing for a human to decide except
which of the donor maps to use when there is more than one.

That choice is made by one rule, stated once here rather than argued
thirty-two times in the table: take the donor map with the LOWEST level band,
because the earliest place the sibling cartridge keeps a species is the one
its own designers thought of as that species' home, and because a row that
lands early cannot be gated harder than the vanilla acquisition it replaces.

Only the ROOT of each line is placed.  Placing EKANS gives ARBOK, because the
mod's renewability closure runs over evolution -- so a row for ARBOK would be
a second spawn for a species the first row already provides.

tests/placements2_test.lua re-derives this block and fails if the checked-in
rows have drifted, so the tool is the thing to edit, never the table.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gapset2 as G  # noqa: E402

BEGIN = "  -- BEGIN SET B -- generated by tools/build_placements2.py"
END = "  -- END SET B"


def wild_locations(root: Path, defines: set[str], valid: set[str]):
    """species -> [(map, kind, lowest level, region)], grass and water."""
    out: dict[str, list[tuple[str, str, int, str]]] = {}
    files = (("johto_grass.asm", "grass", "johto"),
             ("kanto_grass.asm", "grass", "kanto"),
             ("johto_water.asm", "water", "johto"),
             ("kanto_water.asm", "water", "kanto"))
    for name, kind, region in files:
        current = None
        levels: dict[str, int] = {}
        for line in G.read_asm(root / "data" / "wild" / name, defines):
            head = re.search(r"def_(?:grass|water)_wildmons\s+([A-Z0-9_]+)",
                             line)
            if head:
                current = head.group(1)
                levels = {}
                continue
            if not (current and line.strip().startswith("db ")):
                continue
            row = re.match(r"\s*db\s+(\d+)\s*,\s*([A-Z][A-Z0-9_]+)", line)
            if not row:
                continue
            level, species = int(row.group(1)), row.group(2)
            if species not in valid:
                continue
            if levels.get(species, 999) > level:
                levels[species] = level
            entries = out.setdefault(species, [])
            for i, (m, k, lv, rg) in enumerate(entries):
                if m == current and k == kind:
                    if level < lv:
                        entries[i] = (m, k, level, rg)
                    break
            else:
                entries.append((current, kind, level, region))
    return out


def gap_roots(roots: dict[str, Path], order: list[str], valid: set[str]):
    """Per version, one placement per evolution FAMILY inside the gap.

    Not simply "nothing else in the gap reaches it": the mod's closure runs
    up over evolution AND down over the Day-Care, so EKANS reaches ARBOK and
    ARBOK breeds back to EKANS.  Every pair reaches every other pair, and a
    reachability filter would throw the whole family away.

    So the gap's non-trade edges are treated as undirected, the members are
    grouped into families, and each family gets exactly ONE row: its base
    form, the member with no non-trade pre-evolution inside the family.  That
    is the one the player can actually be handed -- placing ARBOK and letting
    the player breed down to EKANS would work, but it puts a fully evolved
    Pokemon in low grass to do it.
    """
    evos = G.evolutions(roots["pokecrystal"], valid)
    parents: dict[str, list[tuple[str, str]]] = {}
    for species, rows in evos.items():
        for method, into in rows:
            parents.setdefault(into, []).append((method, species))

    out = {}
    for version, (tree, defines) in G.VERSIONS.items():
        have = G.renewable(roots[tree], defines, valid)
        gap = {name for name in order if name not in have}

        # union-find over non-trade edges with both ends in the gap
        home: dict[str, str] = {name: name for name in gap}

        def find(name):
            while home[name] != name:
                home[name] = home[home[name]]
                name = home[name]
            return name

        for species, rows in evos.items():
            if species not in gap:
                continue
            for method, into in rows:
                if method == "TRADE" or into not in gap:
                    continue
                a, b = find(species), find(into)
                if a != b:
                    home[a] = b

        families: dict[str, list[str]] = {}
        for name in order:
            if name in gap:
                families.setdefault(find(name), []).append(name)

        roots_here = []
        for members in families.values():
            inside = set(members)
            bases = [n for n in members
                     if not any(method != "TRADE" and parent in inside
                                for method, parent in parents.get(n, []))]
            # A family with no base is one whose only way in is a trade
            # evolution -- the cable's job, not a placement's.
            roots_here.extend(bases or [])
        out[version] = (gap, [n for n in order if n in set(roots_here)])
    return out


def derive(roots: dict[str, Path]):
    order = G.species_names(roots["pokecrystal"])
    valid = set(order)
    located = {
        "gold": wild_locations(roots["pokegold"], {"_GOLD"}, valid),
        "silver": wild_locations(roots["pokegold"], {"_SILVER"}, valid),
        "crystal": wild_locations(roots["pokecrystal"], {"_CRYSTAL"}, valid),
    }
    per_version = gap_roots(roots, order, valid)

    rows = []
    for species in order:
        missing = [v for v in ("gold", "silver", "crystal")
                   if species in per_version[v][1]]
        if not missing:
            continue
        donors = []
        for version, table in located.items():
            if version in missing:
                continue
            donors.extend(table.get(species, []))
        if not donors:
            continue  # nothing to copy: SET A's problem, not this tool's
        # Johto first, then the lowest band, then the map name so the output
        # is stable.  Region leads because the whole of Kanto sits behind the
        # Elite Four in Gen 2: a Johto species whose Kanto route happens to
        # list it one level lower would otherwise be placed behind the entire
        # game, which is not where the sibling cartridge keeps it and not a
        # gate the vanilla acquisition ever charged.
        best = sorted(donors, key=lambda d: (d[3] == "kanto", d[2], d[0]))[0]
        rows.append({
            "species": species, "map": best[0], "method": best[1],
            "region": best[3], "versions": missing,
            "donors": sorted({d[0] for d in donors if d[3] == best[3]}),
        })
    return rows


def render(rows) -> str:
    out = [BEGIN,
           "  --",
           "  -- Do not edit: run tools/build_placements2.py.  Each row is the",
           "  -- map the sibling cartridge keeps this species on, which is the",
           "  -- strongest authority there is -- it is the same game doing the",
           "  -- same thing with the same species.",
           "  --"]
    for row in rows:
        donors = [w for w in ("gold", "silver", "crystal")
                  if w not in row["versions"]]
        subject = " and ".join(w.upper() for w in donors)
        verb = "keeps" if len(donors) == 1 else "keep"
        lost = row["versions"]
        absent = ("%s keeps it nowhere at all" % lost[0].upper()
                  if len(lost) == 1 else
                  "neither %s keeps it anywhere"
                  % " nor ".join(w.upper() for w in lost))
        where = " / ".join(row["donors"])
        why = "%s %s it on %s; %s" % (subject, verb, where, absent)
        out.append('  { species = "%s", map = "%s", method = "%s", '
                   'band = "mid",' % (row["species"], row["map"],
                                      row["method"]))
        out.append('    tier = "UNCOMMON", feature = "exclusives",')
        out.append('    why = "%s" },' % why)
    out.append(END)
    return "\n".join(out)


# The two categories the table deliberately does not carry, restated here so
# --check can prove the gap is fully answered rather than merely consistent.
TRADE_EVOLUTIONS = {"ALAKAZAM", "MACHAMP", "GOLEM", "GENGAR", "POLITOED",
                    "SLOWKING", "STEELIX", "SCIZOR", "KINGDRA", "PORYGON2"}
# Verified against the cartridges rather than assumed, twice over.
#
# Gen 2's only statics are the thirteen `loadwildmon` calls in its map
# scripts, and ARTICUNO, ZAPDOS and MOLTRES are not among them -- listing
# those here would have let --check call a cartridge complete while three
# species had no source at all, which is the exact false pass this constant
# exists to prevent.
#
# What IS answered by modules/Gen251/statics.lua: the three whose object
# script is unguarded, so putting the object back puts the encounter back --
# and the roamers, whose emptied save slot is refilled from the roster.
# SUICUNE is in the second group on GOLD and SILVER, where it roams;
# pokecrystal seeds Raikou and Entei only (src/core/gen2/Roamers.lua:74), so
# on CRYSTAL it is the TIN TOWER static instead and is not answered.
RETRYABLE_STATICS = {"LUGIA", "HO_OH", "SNORLAX", "SUDOWOODO",
                     "RAIKOU", "ENTEI", "SUICUNE"}

# Renewable on the cartridge in a way no wild table can show: LAPRAS is gated
# on DAILYFLAGS2_UNION_CAVE_LAPRAS_F, which is cleared every day, so it is
# back in UNION CAVE B2F every Friday for as long as the save lasts.  It was
# never a gap; the gap set simply cannot see a respawn that lives in a script.
VANILLA_RESPAWNS = {"LAPRAS"}

# Every gap is answered now.  Both of the two that were once listed here as
# known gaps turned out to be answerable, for different reasons:
#
#   SUDOWOODO  the exclusion was based on a wrong reading of `variablesprite`.
#              It swaps the SHEET and nothing else -- the object keeps
#              SudowoodoScript, which reads the SQUIRTBOTTLE and never reads
#              EVENT_FOUGHT_SUDOWOODO -- so putting the object back puts the
#              encounter back, and putting the sprite slot back makes it look
#              right as well.
#   SUICUNE    genuinely cannot be un-hidden on CRYSTAL: its object script is
#              the generic ObjectEvent and the scene that battles it sits
#              behind EVENT_GOT_RAINBOW_WING.  So it is not un-hidden, it is
#              put back where GOLD and SILVER keep it -- the roamers, whose
#              third slot the cart's own CheckEncounterRoamMon already rolls.
KNOWN_GAPS = {}


def coverage(roots: dict[str, Path], table: str):
    """Every gap root on every cartridge is answered by something.

    This is the check worth having: the table can be internally perfect and
    still leave a species unobtainable, which is the one bug the whole mod
    exists to prevent.  A root is answered if it is placed, or if it is one
    of the two categories answered elsewhere.
    """
    order = G.species_names(roots["pokecrystal"])
    valid = set(order)
    placed = set(re.findall(r'species = "([A-Z0-9_]+)"', table))
    per_version = gap_roots(roots, order, valid)
    holes = {}
    for version, (_gap, roots_here) in per_version.items():
        answered = set(placed) | TRADE_EVOLUTIONS | RETRYABLE_STATICS \
            | VANILLA_RESPAWNS
        missing = [name for name in roots_here if name not in answered]
        if missing:
            holes[version] = missing
    return holes


def destinations(roots: dict[str, Path], table: str):
    """Every placement's map must carry a table of its method.

    The one failure this catches is a typo, and a typo here is invisible
    everywhere else: the row loads, the tests pass, the mod installs, and the
    species simply never appears because the map it names has no table to
    substitute inside.  ROUTE_10_NORTH is spelled that way for exactly this
    reason and ROUTE_10 would have failed silently forever.
    """
    order = G.species_names(roots["pokecrystal"])
    valid = set(order)
    rows = re.findall(
        r'species = "([A-Z0-9_]+)", map = "([A-Z0-9_]+)", method = "(\w+)"',
        table)
    known = {}
    for version, (tree, defines) in G.VERSIONS.items():
        maps = {"grass": set(), "water": set()}
        for name, kind in (("johto_grass.asm", "grass"),
                           ("kanto_grass.asm", "grass"),
                           ("johto_water.asm", "water"),
                           ("kanto_water.asm", "water")):
            for line in G.read_asm(roots[tree] / "data" / "wild" / name,
                                   defines):
                head = re.search(
                    r"def_(?:grass|water)_wildmons\s+([A-Z0-9_]+)", line)
                if head:
                    maps[kind].add(head.group(1))
        known[version] = maps

    bad = []
    for species, mapname, method in rows:
        if species not in valid:
            bad.append("%s is not a species" % species)
            continue
        for version, maps in known.items():
            if mapname not in maps.get(method, ()):
                bad.append("%s: %s has no %s table on %s"
                           % (species, mapname, method, version))
    return bad


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--pokegold", required=True, type=Path)
    ap.add_argument("--pokecrystal", required=True, type=Path)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the table has drifted")
    args = ap.parse_args()

    roots = {"pokegold": args.pokegold, "pokecrystal": args.pokecrystal}
    block = render(derive(roots))

    target = Path(__file__).resolve().parent.parent \
        / "modules" / "Gen251" / "placements.lua"
    text = target.read_text()
    if BEGIN not in text or END not in text:
        sys.stderr.write("placements.lua has no SET B markers\n")
        return 1
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + block + tail

    if args.check:
        if updated != text:
            sys.stderr.write("SET B has drifted -- run without --check\n")
            return 1
        wrong = destinations(roots, text)
        if wrong:
            for line in wrong:
                sys.stderr.write(line + "\n")
            return 1
        holes = coverage(roots, text)
        unexpected = {}
        for version, missing in holes.items():
            rest = [name for name in missing if name not in KNOWN_GAPS]
            if rest:
                unexpected[version] = rest
        if unexpected:
            for version, missing in sorted(unexpected.items()):
                sys.stderr.write("%s cannot obtain: %s\n"
                                 % (version, " ".join(missing)))
            return 1
        for version, missing in sorted(holes.items()):
            for name in missing:
                print("  known gap on %s: %s -- %s"
                      % (version, name, KNOWN_GAPS[name]))
        total = sum(len(v) for v in holes.values())
        print("SET B is current, every map named exists, and every gap is "
              "answered%s" % (" apart from the known ones above" if total
                              else " on all three cartridges"))
        return 0

    if updated != text:
        target.write_text(updated)
        print("rewrote SET B")
    else:
        print("SET B was already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
